### ISSUE TITLE
Missing doc of Installation

### ISSUE THREAD

**Issue by longgt** [TemainfoSoftware/truly-ui#254]
**Describe the bug**
Can't start Angular app with Truly-UI.

**To Reproduce**
Following installation, install Truly-UI dependency, add to AppModule and serve.

**Expected behavior**
Truly-UI requires **string-format** and **tl-md5**, **@angular/cdk** as peer dependencies so if this library was not isntalled, **ng serve** always failed.

Peer dependencies, Angular version should be described as
https://github.com/ngx-translate/core (see Installation for more explains)

As Truly-UI is a framework, it should have CHANGELOG file and describe what is BREAKING CHANGES (ex: Angular version...) to help developers in decision whether to upgrade or not.

And it's really amazing if Truly-UI has its own CLI or Starter Kit project.

**Versions(environment versions):**
 - Truly-UI v3.11.0

**Comment by abalad** [comment]
We are very happy that you have installed and tested our framework. 👍 

About dependencies are not actually installed anymore because NPM removes the peerDependencies auto-install support. Plus I updated the documentation with a step that relates to installing them.

Our project uses [Semantic Release](https://github.com/semantic-release/semantic-release), so all changes are listed in the releases link right here on GITHUB, even when there is a BREAKING CHANGES that is listed on each release.

I hope you can use our project more and more because we are still preparing many nice things for him ;)

**Comment by dyhalmeida** [comment]
@abalad I'm going through the same problem integrating truly into my angular application. How can I solve this?

**Comment by abalad** [comment]
Tomorrow I'll be sending a new version that will complete the installation. But by the time you just install the dependencies

**Comment by abalad** [comment]
A correction was sent to the documentation with the correct explanation of how to perform the installation

**Comment by abalad** [comment]
ada

**Comment by abalad** [comment]
aadasdasdasda

**Comment by abalad** [comment]
asdsadasda s

**Comment by abalad** [comment]
asdsadsa dsa dsa sad s
