### ISSUE TITLE
Feature   Truly-ui Vuejs

### ISSUE THREAD

**Issue by vikrampariharcodereadr** [TemainfoSoftware/truly-ui#336]
Hello Team.

This is awesome UI for desktop application. But i like to work in vuejs.
Would you please invest some time for making such beautiful UI in  vuejs. That will definitely appreciatable by developers.

Thank you.
Waiting for response.

**Comment by abalad** [comment]
Hello @vikrampariharcodereadr .

Thank you for the compliments. We are seeking to bring a lot of news to Truly-UI, but the implementation for another LIB is a little out of our scope. We may be creating something for VUE but with another name and another library.

Since we use Truly-UI to develop our company's products, and they are Angular based, recreating Trul-UI would go a long way out of the company's main scope.

Sorry, but I hope you can enjoy Truly-UI on some other future project of yours;)
