### ISSUE TITLE
Ionic icons do not work in ionic application

### ISSUE THREAD

**Issue by Kodzhabashev** [TemainfoSoftware/truly-ui#355]
The selector ion-icon is used by ionic and then ionic icons do no load.
Fix: Change the selector ion-icon to tl-ion-icon

**Comment by abalad** [comment]
Hello, Sorry for the delay, we saw that you sent a PR for the fix, but we need to discuss.

Apparently this bug only happens when Ionic's own LIB is used together with Truly-UI, if so the behavior would be to ignore the truly-ui and prevail the IONIC icons.

What are you trying to use for IONIC icons, Truly-UI or IONIC's own?

**Comment by abalad** [comment]
To use IONIC icons with truly-ui you need to use the following syntax:

`<tl-icon [lib]="'ion'" [style]="'md'">add-circle</tl-icon>`

**Comment by Kodzhabashev** [comment]
Thanks for the reply. 
I have ionic application bit I want to use the truly-ui modal forms. The modal forms have ionic icons integrated in the corner for close, min and max.
In the attached picture you can see how it loads.
<img width="1196" alt="ion-icon" src="https://user-images.githubusercontent.com/51371302/72271125-9f731d00-3626-11ea-9269-271e992d0eed.png">
The issue is that the selectors share the same name. 
I hope that I managed to explain the problem.

**Comment by abalad** [comment]
I'm uploading a run, you can currently reinstall truly-ui using our dev channel: 
npm install truly-ui@dev

**Comment by Kodzhabashev** [comment]
I just tested 4.5.0-dev-2b60105 and it works well. 
Thanks.
